language: go
go:
- 1.8
- 1.9
script:
- go test -v ./...
notifications:
  slack:
    matrix:
    - ruhm-pacino:vcSqblVd1vSDgaOzWLNbThfS
    rooms:
      secure: MFcBuCnXHhFcxYYqLB6zjZMUMGTRF8svChmQHe86qu6i+GtCE52JsJQExr+8DHEnXPuow4LkUtq4iYv4+mhDzbsXB2g/zrs+O4ZnfdlyxNlEUQVxM2vqixQsbLpzDDyW8ijrEmwzzl8S49/ihfZtI4Dj0n1sKy8OkYi8u2AmTqSycn3feJOzv5uZs3CgvQ1hTLTmWh5AfmjKWZlejAC4hIrcoAmtGJC8iyvRyMleYqbPJ2Kn2PZnGTJ0Le9/xx36BZa5JoeYyNQNSesUsFAPoFYR/0SSphNsP/ABy/xN/PikiODbgiH7xuW682dR4VW5xXE9kHYztuwCO+e4O40MAP67OyD78+DIM+U7jNhqsMs0YqBPtpWpcdezdjj7j0URqS+f0ssjRrj3rzbzU1ewMKAR3bWn/d0TbrNjffnC/oCULyVry0jtVLQqrhWd13qhVOJcXDaix/sbv0EfBgLnek8ziH2ik44sRb8KKA0c4+4r9bT/LBMRRtXc+zZORuCVdbd4WUn4X3yUFUwq6JPlf85/hGxQoMafmtaCvUsbQsDS/liq2mhnQB9/HFuwDPj5WW03s/a2jkcsE+Pi28iG2fLZhQaFJPPTAdvM835PWYpa/7S9OfHca6KdGZugjcQQ49MV7UW8y8KJ7nYZyYTPcfa9uJKX2YmcIOsNOBViuug=

